services:
  mysql:
    image: mysql:8.4
    container_name: java-dev-mysql

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: integrador1
      MYSQL_USER: user
      MYSQL_PASSWORD: pwd

    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: